# iom_app.py – IOM Upwind Sail-Trim / VMG Optimizer
# Rewritten with corrected physics and more robust numerics

import streamlit as st
import numpy as np
from scipy.optimize import brentq, differential_evolution
import matplotlib.pyplot as plt

# ------------------------------------------------------------------
# CONSTANTS (simplified IOM-scale model)
# ------------------------------------------------------------------
RHO_AIR   = 1.225        # kg/m³
RHO_WATER = 1025.0       # kg/m³
G         = 9.81         # m/s²

DISPLACEMENT    = 4.0    # kg
SAIL_HEIGHT     = 1.5    # m
SAIL_AREA_MAIN  = 0.22   # m²
SAIL_AREA_JIB   = 0.10   # m²
KEEL_AREA       = 0.015  # m²
KEEL_AR         = 4.0
HYDRO_EFF       = 0.9

# Hull resistance (residuary + frictional lumped)
HULL_CD         = 0.008
HULL_WETTED     = 0.12   # m² approximate wetted area

# Stability
GM              = 0.07   # metacentric height (m) – effective for IOM at small heel

# Centre of effort height fraction (above waterline)
COE_HEIGHT_FRAC = 0.40

# Wind shear
Z_REF           = 1.0
SHEAR_EXP       = 1.0 / 7.0


# ------------------------------------------------------------------
# SAIL AERODYNAMICS
# ------------------------------------------------------------------
def sail_forces(AWA_deg, AWS_ref, sheet_deg, twist_deg, camber, area):
    """
    Compute drive force, side force, and heeling moment for one sail.

    Integrates over height with wind shear, projecting lift/drag at each
    height onto the boat's body axes using the LOCAL apparent wind angle.
    """
    n = 12
    z = np.linspace(0.05, SAIL_HEIGHT, n)
    chord = (area / SAIL_HEIGHT) * np.ones_like(z)

    # Wind shear: AWS grows with height
    V_local = AWS_ref * (z / Z_REF) ** SHEAR_EXP

    # AWA opens slightly with height (boat-speed component shrinks aloft)
    AWA_local_deg = AWA_deg + 2.0 * (z / SAIL_HEIGHT)

    # Twist progressively eases the leech from foot to head
    twist_local_deg = twist_deg * (z / SAIL_HEIGHT)

    # Local angle of attack (radians)
    alpha = np.radians(AWA_local_deg - sheet_deg - twist_local_deg)

    # Thin-airfoil CL with camber offset (camber raises zero-alpha lift)
    CL_inviscid = 2.0 * np.pi * (alpha + 2.0 * camber)

    # Smooth stall rolloff centred at ~16°
    alpha_deg = np.degrees(alpha)
    stall_factor = np.clip(
        1.0 - 0.5 * (1.0 + np.tanh((np.abs(alpha_deg) - 16.0) / 3.0)),
        0.25, 1.0
    )
    CL = CL_inviscid * stall_factor

    # Drag: profile + induced (induced uses sail aspect ratio)
    AR_sail = SAIL_HEIGHT ** 2 / area
    CD = 0.015 + CL ** 2 / (np.pi * 0.85 * AR_sail)

    q = 0.5 * RHO_AIR * V_local ** 2

    # Project locally: lift ⟂ to apparent wind, drag ∥ to it
    awa_rad = np.radians(AWA_local_deg)
    dF_drive = q * chord * (CL * np.sin(awa_rad) - CD * np.cos(awa_rad))
    dF_side  = q * chord * (CL * np.cos(awa_rad) + CD * np.sin(awa_rad))

    # FIXED: np.trapz -> np.trapezoid
    F_drive = np.trapezoid(dF_drive, z)
    F_side  = np.trapezoid(dF_side, z)

    # Heeling moment about waterline: integrate side force × height
    M_heel = np.trapezoid(dF_side * z, z)

    return F_drive, F_side, M_heel


# ------------------------------------------------------------------
# HYDRODYNAMICS
# ------------------------------------------------------------------
def hydro_resistance(Vb, F_side):
    """
    Hull + keel resistance at boat speed Vb with required side force F_side.
    Side force is generated by the keel at some leeway angle; we don't solve
    leeway explicitly but charge induced drag for producing F_side.
    """
    if Vb < 1e-3:
        return 0.0

    q_w = 0.5 * RHO_WATER * Vb ** 2

    # Hull resistance (lumped frictional + residuary)
    R_hull = q_w * HULL_CD * HULL_WETTED

    # Keel: induced drag from producing F_side
    CL_keel = F_side / max(q_w * KEEL_AREA, 1e-6)
    CD_keel = 0.01 + CL_keel ** 2 / (np.pi * HYDRO_EFF * KEEL_AR)
    R_keel = q_w * CD_keel * KEEL_AREA

    return R_hull + R_keel


# ------------------------------------------------------------------
# EQUILIBRIUM
# ------------------------------------------------------------------
def _net_force(Vb, TWA_deg, TWS,
               main_sheet, main_twist, main_camber,
               jib_sheet,  jib_twist,  jib_camber,
               heel_deg):
    """Drive minus resistance at trial speed Vb (with heel feedback)."""
    twa_rad = np.radians(TWA_deg)

    # Apparent wind from true wind triangle
    awa_rad = np.arctan2(
        TWS * np.sin(twa_rad),
        TWS * np.cos(twa_rad) - Vb
    )

    AWA_deg = np.degrees(awa_rad)

    AWS = np.hypot(
        TWS * np.sin(twa_rad),
        TWS * np.cos(twa_rad) - Vb
    )

    # Heel reduces effective driving force
    cos_heel = np.cos(np.radians(heel_deg))

    Fm_d, Fm_s, Mm = sail_forces(
        AWA_deg, AWS,
        main_sheet, main_twist, main_camber,
        SAIL_AREA_MAIN
    )

    Fj_d, Fj_s, Mj = sail_forces(
        AWA_deg + 4, AWS,
        jib_sheet, jib_twist, jib_camber,
        SAIL_AREA_JIB
    )

    F_drive = (Fm_d + Fj_d) * cos_heel
    F_side  = (Fm_s + Fj_s) * cos_heel
    M_heel  = (Mm + Mj) * cos_heel

    R = hydro_resistance(Vb, F_side)

    return F_drive - R, F_side, M_heel


def boat_equilibrium(TWA_deg, TWS,
                     main_sheet, main_twist, main_camber,
                     jib_sheet,  jib_twist,  jib_camber):
    """
    Solve for steady-state boat speed and heel.
    """
    heel_deg = 0.0

    for _ in range(8):

        def residual(Vb):
            net, _, _ = _net_force(
                Vb, TWA_deg, TWS,
                main_sheet, main_twist, main_camber,
                jib_sheet, jib_twist, jib_camber,
                heel_deg
            )
            return net

        try:
            r_lo = residual(0.05)
            r_hi = residual(6.0)

            if r_lo * r_hi > 0:
                Vb = 0.0
                break

            Vb = brentq(
                residual,
                0.05, 6.0,
                xtol=1e-3,
                maxiter=50
            )

        except (ValueError, RuntimeError):
            Vb = 0.0
            break

        _, F_side, M_heel = _net_force(
            Vb, TWA_deg, TWS,
            main_sheet, main_twist, main_camber,
            jib_sheet, jib_twist, jib_camber,
            heel_deg
        )

        ratio = M_heel / max(DISPLACEMENT * G * GM, 1e-6)
        ratio = np.clip(ratio, -0.999, 0.999)

        new_heel = np.degrees(np.arcsin(ratio))

        if abs(new_heel - heel_deg) < 0.2:
            heel_deg = new_heel
            break

        heel_deg = 0.5 * heel_deg + 0.5 * new_heel

    return max(Vb, 0.0), heel_deg
